#include "Categorie.h"




int Categorie::getIdentifiant()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A08 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A08 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Categorie::getLabel()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A0A begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A0A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Categorie::setLabel(String lab)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A42 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A42 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
