#include "Espece.h"

int Espece::getIdentifiant()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009ED begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009ED end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Espece::getType()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009F0 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009F0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Espece::getRegimeAlimentaire()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A35 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A35 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Espece::getInformation()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A37 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A37 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Espece::setType(int type)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A39 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A39 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Espece::setRegimeAlimentaire(char * ra)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A3C begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A3C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Espece::setInformation(char * inf)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A3F begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A3F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
