#include "ListeQuestion.h"




Question ListeQuestion::getElementById(int id)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A48 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A48 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
