#include "ListeMedia.h"




Media ListeMedia::getElementById(int id)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A4B begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A4B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Media ListeMedia::getElementByPath(char * path)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A54 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A54 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
