#include "Media.h"




int Media::getIdentifiant()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A0E begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A0E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Media::getType()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A10 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A10 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Media::setType(int t)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A12 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A12 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
