#include "Question.h"




int Question::getIdentifiant()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009FC begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009FC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Question::getQuestion()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009FE begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009FE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Question::ajouterReponse(Reponse rep)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A00 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A00 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Question::supprimerReponse(Reponse rep)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A02 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A02 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Question::ajouterMedia(Media med)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A04 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A04 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Question::supprimerMedia(Media med)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A06 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A06 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Question::setQuestion(char * question)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A2A begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A2A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
