#include "QuestionBDD.h"




ListeQuestion QuestionBDD::CreerArbre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1-109-676f4621:136158eb819:-8000:00000000000009D6 begin
{
}
// section -84-25-1-109-676f4621:136158eb819:-8000:00000000000009D6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
