#include "Reponse.h"




int Reponse::getIdentifiant()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009F2 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009F2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Reponse::getReponse()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009F4 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009F4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Reponse::AjouterMedia(Media media)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009F6 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009F6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Reponse::SupprimerMedia(int id)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009F9 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:00000000000009F9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Question Reponse::getQuestionSuiv()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A15 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A15 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Question Reponse::getQuestionPrec()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A17 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A17 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

ListeMedia Reponse::getListeIllustration()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A19 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A19 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Reponse::setReponse(String rep)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A1B begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A1B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Reponse::setQuestionSuiv(Question question)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A1E begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A1E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Reponse::setQuestionPrec(Question question)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A21 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A21 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Reponse::ajouterMedia(Media med)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A24 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A24 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Reponse::supprimerMedia(Media med)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A27 begin
{
}
// section -84-25-1--85-30f4179f:1362a6755e8:-8000:0000000000000A27 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
